### ISSUE TITLE
v1.4) 후원기능에 접근 시도하면 Error 23 발생

### ISSUE THREAD

**Issue by distilledliquor** [Beomi/SmartSpamFilter-QnA#1]
iPhone 15 Pro Max 1TB 한국모델 + iOS 17.6 (21G5066d) 조합입니다

**Comment by Beomi** [comment]
제보 감사합니다! ㅠㅠㅠ 이거 애플이... 앱은 승인해주고 인앱결제를 승인 안해주는 실수(?)를 해서... 하루이틀 걸릴것 같아요 🥲🥲

후원 시도 정말 감사합니다!!!!
