### ISSUE TITLE
경품 당첨 문자가 스팸으로 분류 처리되어서 당첨 취소 되었습니다.

### ISSUE THREAD

**Issue by sophie12345678010** [Beomi/SmartSpamFilter-QnA#3]
경품 당첨 안내 문자가 왔었는데 어플이 스팸으로 분류해 회신이 없어 당첨 취소되었습니다. 
아이패드 당첨이었는데요......

**Comment by Beomi** [comment]
..😱😱😱🤯
세상에 그런 일이....

뭐라 드릴 말씀이 없네요ㅠㅠㅠ..

스팸필터의 목적이 스팸에서 사용자분들을 보호하는게 목적이지만 새로운 유형에 보다 잘 대응하도록 만드는게 쉽지가 않네요.. 정말 안타깝게 생각합니다.

이미 정말 늦은 일이지만 앞으로 AI가 비슷한 문자를 스팸으로 보지 않을 수 있게, 혹시 발신자 번호와 문자 내용을 알려주시면 다음 모델 업데이트에 바로 반영하고자 합니다...

참 뭐라 말씀드리기 어렵네요.. 정말 상상도 못한 케이스라..ㅠㅠㅠ
죄송하다는 말밖에 드릴수가 없어서 더 죄송합니다 ㅜ ㅜ

**Comment by sophie12345678010** [comment]
한순간에 기뻤다가...한순간에 기분이 뭐라 말할수없을 정도로 속상하네요....ㅎ..ㅏ.....



2024년 7월 24일 (수) 오후 11:14, Junbum Lee ***@***.***>님이 작성:

**Comment by sophie12345678010** [comment]
이거 방금 메일로 첨부해서 보냈는데 된건가요?

2024년 7월 24일 (수) 오후 11:14, Junbum Lee ***@***.***>님이 작성:

**Comment by Beomi** [comment]
혹시 jun@beomi.net 으로 보내주시면 확인이 용이할것 같습니다 .... 

ㅠㅠ 너무 .. 안타깝고 죄송한 마음입니다..
